### ISSUE TITLE
[Parchment] Unable to create table-up-col blot

### ISSUE THREAD

**Issue by natanspricigo** [zzxming/quill-table-up#50]
I'm setting up table-up, but when I click to insert a table, it gets lost and throws this error:
### parchment.js:54 Uncaught ParchmentError: [Parchment] Unable to create table-up-col blot

My code
```javascript
let formats = [
    'header',
    'bold', 'italic', 'underline', 'strike', 'blockquote',
    'list', 'bullet', 'indent', 'align', 'color', 'background', 'clean',
    'link', 'image', TableUp.toolName
];
``` 

```javascript
let modules = {
    table: true,
    toolbar: [
        ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
        [{ 'align': [] }],
        [{ 'indent': '-1' }, { 'indent': '+1' }],          // outdent/indent
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
        [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
        ['clean'],
        ['image'],
        [{[TableUp.toolName]: []}]
    ],
    imageResize: {
        modules: ['Resize', 'DisplaySize' /*, 'Toolbar'*/],
        handleStyles: {
            backgroundColor: 'black',
            border: 'none',
            color: 'white',
            displaySize: true,
        }
    },
    clipboard: {
        // toggle to add extra line breaks when pasting HTML:
        matchVisual: false,
    },
    [TableUp.moduleName]: {
        scrollbar: TableVirtualScrollbar,
        full: false,
        customBtn: true,
        align: TableAlign,
        resize: TableResizeBox,
        resizeScale: TableResizeScale,
        selection: TableSelection,
        customSelect: defaultCustomSelect,
        selectionOptions: {
            tableMenu: TableMenuContextmenu
        }
    },
};
```

```javascript
const { quill, quillRef, Quill } = useQuill({ theme, modules, formats, placeholder });
    if (Quill && !quill) { // For execute this line only once.
        Quill.register('modules/imageResize', ImageResize, false);
        Quill.register('modules/table-up', TableUp, true);
    }
```

This error occurs when inserting the table or trying to force start with the content:

```javascript
quill.setContents([
                { insert: '\n' },
                { insert: { 'table-up-col': { tableId: '8v36875pbr6', colId: '1vwhsx9zayhi', full: true, width: 20 } } }
               ]);
```

Libs
```javascript
... 
"quill": "^2.0.0",
    "quill-image-resize-module-react": "^3.0.0",
    "quill-mention": "^6.0.2",
    "quill-table-up": "^2.0.1",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-quilljs": "^2.0.5",
...
```
Estou usando uma biblioteca para React
https://github.com/gtgalone/react-quilljs

It renders everything correctly, and the other modules work.
What could it be?

**Comment by zzxming** [comment]
this error beacuse your use the `formats` option. table does not only use the blot `TableUp.toolName`. you may need write `formats` like this: 

```ts
import { blotName } from 'quill-table-up';

let formats = [
    'header',
    'bold', 'italic', 'underline', 'strike', 'blockquote',
    'list', 'bullet', 'indent', 'align', 'color', 'background', 'clean',
    'link', 'image', ...Object.values(blotName)
];
```

**Comment by natanspricigo** [comment]
OK, I'll test it
do I do this for all the table-up blots?
thanks in advance!

**Comment by natanspricigo** [comment]
Now it's working as expected, with this fix that was passed.

```javascript
import TableUp, { TableAlign, TableMenuContextmenu, TableResizeBox, TableResizeScale, TableSelection, TableVirtualScrollbar, blotName, defaultCustomSelect } from 'quill-table-up';

let formats = [
    'header',
    'bold', 'italic', 'underline', 'strike', 'blockquote',
    'list', 'bullet', 'indent', 'align', 'color', 'background', 'clean',
    'link', 'image', TableUp.toolName, ...Object.values(blotName)
];

```

The only thing is when I try to resize it with the mouse, it gives an error:

```text
Uncaught TypeError: Cannot read properties of null (reading 'index')
quill.js:291 Uncaught TypeError: Cannot read properties of null (reading 'index')
at Quill.getFormat (quill.js:291:1)
at r (index.js:4117:1)
at clipboard.js:271:1
```

Do I need to add any blot?

**Comment by zzxming** [comment]
Can you create a repo like use [https://stackblitz.com/](https://stackblitz.com/). my test code like [this](https://stackblitz.com/edit/vitejs-vite-sax5yo4x?file=src%2FApp.tsx). it's work
